/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateMatchInput {
  'scheduledTime' : Timestamp,
  'name' : string,
  'roomPassword' : string,
  'entryFee' : bigint,
  'roomId' : string,
  'prizePool' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface MatchCredentials { 'roomPassword' : string, 'roomId' : string }
export type MatchId = string;
export interface MatchPublic {
  'id' : MatchId,
  'status' : MatchStatus,
  'scheduledTime' : Timestamp,
  'name' : string,
  'createdAt' : Timestamp,
  'playerCount' : bigint,
  'entryFee' : bigint,
  'prizePool' : bigint,
}
export type MatchStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'completed' : null };
export type PaymentId = string;
export interface PaymentPublic {
  'id' : PaymentId,
  'status' : PaymentStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'matchId' : MatchId,
  'utrNumber' : string,
  'screenshot' : ExternalBlob,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface RegisterInput {
  'contact' : string,
  'username' : string,
  'password' : string,
  'ffUid' : string,
}
export interface Result {
  'id' : ResultId,
  'username' : string,
  'userId' : UserId,
  'rank' : bigint,
  'matchId' : MatchId,
  'prize' : bigint,
  'kills' : bigint,
}
export type ResultId = string;
export interface ResultInput {
  'username' : string,
  'userId' : UserId,
  'rank' : bigint,
  'prize' : bigint,
  'kills' : bigint,
}
export interface SubmitPaymentInput {
  'matchId' : MatchId,
  'utrNumber' : string,
  'screenshot' : ExternalBlob,
}
export type Timestamp = bigint;
export interface UpdateMatchInput {
  'scheduledTime' : [] | [Timestamp],
  'name' : [] | [string],
  'roomPassword' : [] | [string],
  'entryFee' : [] | [bigint],
  'roomId' : [] | [string],
  'prizePool' : [] | [bigint],
}
export interface UpdateProfileInput {
  'username' : [] | [string],
  'password' : [] | [string],
  'ffUid' : [] | [string],
}
export type UserId = string;
export interface UserPublic {
  'id' : UserId,
  'status' : UserStatus,
  'contact' : string,
  'username' : string,
  'createdAt' : Timestamp,
  'walletBalance' : bigint,
  'ffUid' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'suspended' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approvePayment' : ActorMethod<[PaymentId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeMatch' : ActorMethod<[MatchId], undefined>,
  'createMatch' : ActorMethod<[CreateMatchInput], MatchPublic>,
  'deleteMatch' : ActorMethod<[MatchId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatch' : ActorMethod<[MatchId], [] | [MatchPublic]>,
  'getMatchPlayers' : ActorMethod<[MatchId], Array<UserId>>,
  'getMatchResults' : ActorMethod<[MatchId], Array<Result>>,
  'getMyPayments' : ActorMethod<[], Array<PaymentPublic>>,
  'getMyProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getRoomCredentials' : ActorMethod<[MatchId], MatchCredentials>,
  'getUserById' : ActorMethod<[UserId], [] | [UserPublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllPayments' : ActorMethod<[], Array<PaymentPublic>>,
  'listMatches' : ActorMethod<[], Array<MatchPublic>>,
  'listPaymentsByMatch' : ActorMethod<[MatchId], Array<PaymentPublic>>,
  'listUsers' : ActorMethod<[], Array<UserPublic>>,
  'loginUser' : ActorMethod<[string, string], [] | [UserPublic]>,
  'register' : ActorMethod<[RegisterInput], UserPublic>,
  'rejectPayment' : ActorMethod<[PaymentId], undefined>,
  'submitPayment' : ActorMethod<[SubmitPaymentInput], PaymentPublic>,
  'suspendUser' : ActorMethod<[UserId], undefined>,
  'unsuspendUser' : ActorMethod<[UserId], undefined>,
  'updateMatch' : ActorMethod<[MatchId, UpdateMatchInput], MatchPublic>,
  'updateMyProfile' : ActorMethod<[UpdateProfileInput], UserPublic>,
  'uploadResults' : ActorMethod<[MatchId, Array<ResultInput>], Array<Result>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];