/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PaymentId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchId = IDL.Text;
export const Timestamp = IDL.Int;
export const CreateMatchInput = IDL.Record({
  'scheduledTime' : Timestamp,
  'name' : IDL.Text,
  'roomPassword' : IDL.Text,
  'entryFee' : IDL.Nat,
  'roomId' : IDL.Text,
  'prizePool' : IDL.Nat,
});
export const MatchStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
});
export const MatchPublic = IDL.Record({
  'id' : MatchId,
  'status' : MatchStatus,
  'scheduledTime' : Timestamp,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'playerCount' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'prizePool' : IDL.Nat,
});
export const UserId = IDL.Text;
export const ResultId = IDL.Text;
export const Result = IDL.Record({
  'id' : ResultId,
  'username' : IDL.Text,
  'userId' : UserId,
  'rank' : IDL.Nat,
  'matchId' : MatchId,
  'prize' : IDL.Nat,
  'kills' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PaymentPublic = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'matchId' : MatchId,
  'utrNumber' : IDL.Text,
  'screenshot' : ExternalBlob,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'suspended' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'contact' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'walletBalance' : IDL.Nat,
  'ffUid' : IDL.Text,
});
export const MatchCredentials = IDL.Record({
  'roomPassword' : IDL.Text,
  'roomId' : IDL.Text,
});
export const RegisterInput = IDL.Record({
  'contact' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'ffUid' : IDL.Text,
});
export const SubmitPaymentInput = IDL.Record({
  'matchId' : MatchId,
  'utrNumber' : IDL.Text,
  'screenshot' : ExternalBlob,
});
export const UpdateMatchInput = IDL.Record({
  'scheduledTime' : IDL.Opt(Timestamp),
  'name' : IDL.Opt(IDL.Text),
  'roomPassword' : IDL.Opt(IDL.Text),
  'entryFee' : IDL.Opt(IDL.Nat),
  'roomId' : IDL.Opt(IDL.Text),
  'prizePool' : IDL.Opt(IDL.Nat),
});
export const UpdateProfileInput = IDL.Record({
  'username' : IDL.Opt(IDL.Text),
  'password' : IDL.Opt(IDL.Text),
  'ffUid' : IDL.Opt(IDL.Text),
});
export const ResultInput = IDL.Record({
  'username' : IDL.Text,
  'userId' : UserId,
  'rank' : IDL.Nat,
  'prize' : IDL.Nat,
  'kills' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approvePayment' : IDL.Func([PaymentId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeMatch' : IDL.Func([MatchId], [], []),
  'createMatch' : IDL.Func([CreateMatchInput], [MatchPublic], []),
  'deleteMatch' : IDL.Func([MatchId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatch' : IDL.Func([MatchId], [IDL.Opt(MatchPublic)], ['query']),
  'getMatchPlayers' : IDL.Func([MatchId], [IDL.Vec(UserId)], ['query']),
  'getMatchResults' : IDL.Func([MatchId], [IDL.Vec(Result)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getRoomCredentials' : IDL.Func([MatchId], [MatchCredentials], ['query']),
  'getUserById' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
  'listMatches' : IDL.Func([], [IDL.Vec(MatchPublic)], ['query']),
  'listPaymentsByMatch' : IDL.Func(
      [MatchId],
      [IDL.Vec(PaymentPublic)],
      ['query'],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(UserPublic)], []),
  'register' : IDL.Func([RegisterInput], [UserPublic], []),
  'rejectPayment' : IDL.Func([PaymentId], [], []),
  'submitPayment' : IDL.Func([SubmitPaymentInput], [PaymentPublic], []),
  'suspendUser' : IDL.Func([UserId], [], []),
  'unsuspendUser' : IDL.Func([UserId], [], []),
  'updateMatch' : IDL.Func([MatchId, UpdateMatchInput], [MatchPublic], []),
  'updateMyProfile' : IDL.Func([UpdateProfileInput], [UserPublic], []),
  'uploadResults' : IDL.Func(
      [MatchId, IDL.Vec(ResultInput)],
      [IDL.Vec(Result)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PaymentId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchId = IDL.Text;
  const Timestamp = IDL.Int;
  const CreateMatchInput = IDL.Record({
    'scheduledTime' : Timestamp,
    'name' : IDL.Text,
    'roomPassword' : IDL.Text,
    'entryFee' : IDL.Nat,
    'roomId' : IDL.Text,
    'prizePool' : IDL.Nat,
  });
  const MatchStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
  });
  const MatchPublic = IDL.Record({
    'id' : MatchId,
    'status' : MatchStatus,
    'scheduledTime' : Timestamp,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'playerCount' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  const UserId = IDL.Text;
  const ResultId = IDL.Text;
  const Result = IDL.Record({
    'id' : ResultId,
    'username' : IDL.Text,
    'userId' : UserId,
    'rank' : IDL.Nat,
    'matchId' : MatchId,
    'prize' : IDL.Nat,
    'kills' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PaymentPublic = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'matchId' : MatchId,
    'utrNumber' : IDL.Text,
    'screenshot' : ExternalBlob,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'contact' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'walletBalance' : IDL.Nat,
    'ffUid' : IDL.Text,
  });
  const MatchCredentials = IDL.Record({
    'roomPassword' : IDL.Text,
    'roomId' : IDL.Text,
  });
  const RegisterInput = IDL.Record({
    'contact' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'ffUid' : IDL.Text,
  });
  const SubmitPaymentInput = IDL.Record({
    'matchId' : MatchId,
    'utrNumber' : IDL.Text,
    'screenshot' : ExternalBlob,
  });
  const UpdateMatchInput = IDL.Record({
    'scheduledTime' : IDL.Opt(Timestamp),
    'name' : IDL.Opt(IDL.Text),
    'roomPassword' : IDL.Opt(IDL.Text),
    'entryFee' : IDL.Opt(IDL.Nat),
    'roomId' : IDL.Opt(IDL.Text),
    'prizePool' : IDL.Opt(IDL.Nat),
  });
  const UpdateProfileInput = IDL.Record({
    'username' : IDL.Opt(IDL.Text),
    'password' : IDL.Opt(IDL.Text),
    'ffUid' : IDL.Opt(IDL.Text),
  });
  const ResultInput = IDL.Record({
    'username' : IDL.Text,
    'userId' : UserId,
    'rank' : IDL.Nat,
    'prize' : IDL.Nat,
    'kills' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approvePayment' : IDL.Func([PaymentId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeMatch' : IDL.Func([MatchId], [], []),
    'createMatch' : IDL.Func([CreateMatchInput], [MatchPublic], []),
    'deleteMatch' : IDL.Func([MatchId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatch' : IDL.Func([MatchId], [IDL.Opt(MatchPublic)], ['query']),
    'getMatchPlayers' : IDL.Func([MatchId], [IDL.Vec(UserId)], ['query']),
    'getMatchResults' : IDL.Func([MatchId], [IDL.Vec(Result)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getRoomCredentials' : IDL.Func([MatchId], [MatchCredentials], ['query']),
    'getUserById' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
    'listMatches' : IDL.Func([], [IDL.Vec(MatchPublic)], ['query']),
    'listPaymentsByMatch' : IDL.Func(
        [MatchId],
        [IDL.Vec(PaymentPublic)],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(UserPublic)], []),
    'register' : IDL.Func([RegisterInput], [UserPublic], []),
    'rejectPayment' : IDL.Func([PaymentId], [], []),
    'submitPayment' : IDL.Func([SubmitPaymentInput], [PaymentPublic], []),
    'suspendUser' : IDL.Func([UserId], [], []),
    'unsuspendUser' : IDL.Func([UserId], [], []),
    'updateMatch' : IDL.Func([MatchId, UpdateMatchInput], [MatchPublic], []),
    'updateMyProfile' : IDL.Func([UpdateProfileInput], [UserPublic], []),
    'uploadResults' : IDL.Func(
        [MatchId, IDL.Vec(ResultInput)],
        [IDL.Vec(Result)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };