/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MatchCredentials {
    roomPassword: string;
    roomId: string;
}
export interface ResultInput {
    username: string;
    userId: UserId;
    rank: bigint;
    prize: bigint;
    kills: bigint;
}
export type Timestamp = bigint;
export interface UserPublic {
    id: UserId;
    status: UserStatus;
    contact: string;
    username: string;
    createdAt: Timestamp;
    walletBalance: bigint;
    ffUid: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaymentPublic {
    id: PaymentId;
    status: PaymentStatus;
    userId: UserId;
    createdAt: Timestamp;
    matchId: MatchId;
    utrNumber: string;
    screenshot: ExternalBlob;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type ResultId = string;
export type MatchId = string;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserId = string;
export interface CreateMatchInput {
    scheduledTime: Timestamp;
    name: string;
    roomPassword: string;
    entryFee: bigint;
    roomId: string;
    prizePool: bigint;
}
export interface Result {
    id: ResultId;
    username: string;
    userId: UserId;
    rank: bigint;
    matchId: MatchId;
    prize: bigint;
    kills: bigint;
}
export interface UpdateProfileInput {
    username?: string;
    password?: string;
    ffUid?: string;
}
export type PaymentId = string;
export interface SubmitPaymentInput {
    matchId: MatchId;
    utrNumber: string;
    screenshot: ExternalBlob;
}
export interface RegisterInput {
    contact: string;
    username: string;
    password: string;
    ffUid: string;
}
export interface MatchPublic {
    id: MatchId;
    status: MatchStatus;
    scheduledTime: Timestamp;
    name: string;
    createdAt: Timestamp;
    playerCount: bigint;
    entryFee: bigint;
    prizePool: bigint;
}
export interface UpdateMatchInput {
    scheduledTime?: Timestamp;
    name?: string;
    roomPassword?: string;
    entryFee?: bigint;
    roomId?: string;
    prizePool?: bigint;
}
export enum MatchStatus {
    closed = "closed",
    open = "open",
    completed = "completed"
}
export enum PaymentStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    suspended = "suspended"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    approvePayment(paymentId: PaymentId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    closeMatch(matchId: MatchId): Promise<void>;
    createMatch(input: CreateMatchInput): Promise<MatchPublic>;
    deleteMatch(matchId: MatchId): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getMatch(matchId: MatchId): Promise<MatchPublic | null>;
    getMatchPlayers(matchId: MatchId): Promise<Array<UserId>>;
    getMatchResults(matchId: MatchId): Promise<Array<Result>>;
    getMyPayments(): Promise<Array<PaymentPublic>>;
    getMyProfile(): Promise<UserPublic | null>;
    getRoomCredentials(matchId: MatchId): Promise<MatchCredentials>;
    getUserById(userId: UserId): Promise<UserPublic | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllPayments(): Promise<Array<PaymentPublic>>;
    listMatches(): Promise<Array<MatchPublic>>;
    listPaymentsByMatch(matchId: MatchId): Promise<Array<PaymentPublic>>;
    listUsers(): Promise<Array<UserPublic>>;
    loginUser(identifier: string, password: string): Promise<UserPublic | null>;
    register(input: RegisterInput): Promise<UserPublic>;
    rejectPayment(paymentId: PaymentId): Promise<void>;
    submitPayment(input: SubmitPaymentInput): Promise<PaymentPublic>;
    suspendUser(userId: UserId): Promise<void>;
    unsuspendUser(userId: UserId): Promise<void>;
    updateMatch(matchId: MatchId, input: UpdateMatchInput): Promise<MatchPublic>;
    updateMyProfile(input: UpdateProfileInput): Promise<UserPublic>;
    uploadResults(matchId: MatchId, entries: Array<ResultInput>): Promise<Array<Result>>;
}
import type { ExternalBlob as _ExternalBlob, MatchId as _MatchId, MatchPublic as _MatchPublic, MatchStatus as _MatchStatus, PaymentId as _PaymentId, PaymentPublic as _PaymentPublic, PaymentStatus as _PaymentStatus, SubmitPaymentInput as _SubmitPaymentInput, Timestamp as _Timestamp, UpdateMatchInput as _UpdateMatchInput, UpdateProfileInput as _UpdateProfileInput, UserId as _UserId, UserPublic as _UserPublic, UserRole as _UserRole, UserStatus as _UserStatus, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async approvePayment(arg0: PaymentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePayment(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async closeMatch(arg0: MatchId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeMatch(arg0);
            return result;
        }
    }
    async createMatch(arg0: CreateMatchInput): Promise<MatchPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0);
                return from_candid_MatchPublic_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0);
            return from_candid_MatchPublic_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMatch(arg0: MatchId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: MatchId): Promise<MatchPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchPlayers(arg0: MatchId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchPlayers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchPlayers(arg0);
            return result;
        }
    }
    async getMatchResults(arg0: MatchId): Promise<Array<Result>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchResults(arg0);
            return result;
        }
    }
    async getMyPayments(): Promise<Array<PaymentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPayments();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPayments();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomCredentials(arg0: MatchId): Promise<MatchCredentials> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomCredentials(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomCredentials(arg0);
            return result;
        }
    }
    async getUserById(arg0: UserId): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllPayments(): Promise<Array<PaymentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPayments();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPayments();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMatches(): Promise<Array<MatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMatches();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMatches();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPaymentsByMatch(arg0: MatchId): Promise<Array<PaymentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPaymentsByMatch(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPaymentsByMatch(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: RegisterInput): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return from_candid_UserPublic_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return from_candid_UserPublic_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectPayment(arg0: PaymentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPayment(arg0);
            return result;
        }
    }
    async submitPayment(arg0: SubmitPaymentInput): Promise<PaymentPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPayment(await to_candid_SubmitPaymentInput_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PaymentPublic_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPayment(await to_candid_SubmitPaymentInput_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PaymentPublic_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async suspendUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0);
            return result;
        }
    }
    async unsuspendUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsuspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsuspendUser(arg0);
            return result;
        }
    }
    async updateMatch(arg0: MatchId, arg1: UpdateMatchInput): Promise<MatchPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatch(arg0, to_candid_UpdateMatchInput_n33(this._uploadFile, this._downloadFile, arg1));
                return from_candid_MatchPublic_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatch(arg0, to_candid_UpdateMatchInput_n33(this._uploadFile, this._downloadFile, arg1));
            return from_candid_MatchPublic_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: UpdateProfileInput): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_UpdateProfileInput_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserPublic_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_UpdateProfileInput_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserPublic_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadResults(arg0: MatchId, arg1: Array<ResultInput>): Promise<Array<Result>> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadResults(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadResults(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MatchPublic_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchPublic): MatchPublic {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_PaymentPublic_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentPublic): Promise<PaymentPublic> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchPublic]): MatchPublic | null {
    return value.length === 0 ? null : from_candid_MatchPublic_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MatchId;
    status: _MatchStatus;
    scheduledTime: _Timestamp;
    name: string;
    createdAt: _Timestamp;
    playerCount: bigint;
    entryFee: bigint;
    prizePool: bigint;
}): {
    id: MatchId;
    status: MatchStatus;
    scheduledTime: Timestamp;
    name: string;
    createdAt: Timestamp;
    playerCount: bigint;
    entryFee: bigint;
    prizePool: bigint;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n12(_uploadFile, _downloadFile, value.status),
        scheduledTime: value.scheduledTime,
        name: value.name,
        createdAt: value.createdAt,
        playerCount: value.playerCount,
        entryFee: value.entryFee,
        prizePool: value.prizePool
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    status: _PaymentStatus;
    userId: _UserId;
    createdAt: _Timestamp;
    matchId: _MatchId;
    utrNumber: string;
    screenshot: _ExternalBlob;
}): Promise<{
    id: PaymentId;
    status: PaymentStatus;
    userId: UserId;
    createdAt: Timestamp;
    matchId: MatchId;
    utrNumber: string;
    screenshot: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n20(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        matchId: value.matchId,
        utrNumber: value.utrNumber,
        screenshot: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.screenshot)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _UserStatus;
    contact: string;
    username: string;
    createdAt: _Timestamp;
    walletBalance: bigint;
    ffUid: string;
}): {
    id: UserId;
    status: UserStatus;
    contact: string;
    username: string;
    createdAt: Timestamp;
    walletBalance: bigint;
    ffUid: string;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n26(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        username: value.username,
        createdAt: value.createdAt,
        walletBalance: value.walletBalance,
        ffUid: value.ffUid
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    completed: null;
}): MatchStatus {
    return "closed" in value ? MatchStatus.closed : "open" in value ? MatchStatus.open : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "approved" in value ? PaymentStatus.approved : "rejected" in value ? PaymentStatus.rejected : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    suspended: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "suspended" in value ? UserStatus.suspended : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentPublic>): Promise<Array<PaymentPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PaymentPublic_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchPublic>): Array<MatchPublic> {
    return value.map((x)=>from_candid_MatchPublic_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPublic>): Array<UserPublic> {
    return value.map((x)=>from_candid_UserPublic_n24(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_SubmitPaymentInput_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitPaymentInput): Promise<_SubmitPaymentInput> {
    return await to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateMatchInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateMatchInput): _UpdateMatchInput {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileInput_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileInput): _UpdateProfileInput {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchId: MatchId;
    utrNumber: string;
    screenshot: ExternalBlob;
}): Promise<{
    matchId: _MatchId;
    utrNumber: string;
    screenshot: _ExternalBlob;
}> {
    return {
        matchId: value.matchId,
        utrNumber: value.utrNumber,
        screenshot: await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.screenshot)
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduledTime?: Timestamp;
    name?: string;
    roomPassword?: string;
    entryFee?: bigint;
    roomId?: string;
    prizePool?: bigint;
}): {
    scheduledTime: [] | [_Timestamp];
    name: [] | [string];
    roomPassword: [] | [string];
    entryFee: [] | [bigint];
    roomId: [] | [string];
    prizePool: [] | [bigint];
} {
    return {
        scheduledTime: value.scheduledTime ? candid_some(value.scheduledTime) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        roomPassword: value.roomPassword ? candid_some(value.roomPassword) : candid_none(),
        entryFee: value.entryFee ? candid_some(value.entryFee) : candid_none(),
        roomId: value.roomId ? candid_some(value.roomId) : candid_none(),
        prizePool: value.prizePool ? candid_some(value.prizePool) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username?: string;
    password?: string;
    ffUid?: string;
}): {
    username: [] | [string];
    password: [] | [string];
    ffUid: [] | [string];
} {
    return {
        username: value.username ? candid_some(value.username) : candid_none(),
        password: value.password ? candid_some(value.password) : candid_none(),
        ffUid: value.ffUid ? candid_some(value.ffUid) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
